Repository BSU-SUITS-Team/ARSIS, pull requests merged in 2024-02, with the labels that each got.

#197 Implemented GET request for ROVER
  ARSIS-Telemetry-GroundControl/groundcontrol-api/app/tss.py
Labels: mcp

#196 Implemented GET request for IMU
  ARSIS-Telemetry-GroundControl/groundcontrol-api/app/tss.py
Labels: mcp

#202 Removed "eva_" from telemetry table
  ARSIS-Telemetry-GroundControl/groundcontrol-db/database.sql
Labels: mcp

#203 Lmcc updates
  ARSIS-Telemetry-GroundControl/LMCC/src/lib/biometrics.js
  ARSIS-Telemetry-GroundControl/LMCC/src/routes/biometrics/+page.svelte
  ARSIS-Telemetry-GroundControl/LMCC/src/routes/biometricsgraph/+page.svelte
  ARSIS-Telemetry-GroundControl/LMCC/src/routes/biometricsgraph/chart.svelte
Labels: LMCC

#213 Implement readonly WebSocket client for HMD
  ARSIS-Telemetry-GroundControl/groundcontrol-db/database.sql
  ARSIS-Unity/.vsconfig
  ARSIS-Unity/Assets/Scenes/SampleScene.unity
  ARSIS-Unity/Assets/Scripts.meta
  ARSIS-Unity/Assets/Scripts/EventManager.meta
  ARSIS-Unity/Assets/Scripts/EventManager/EventManager.cs
  ARSIS-Unity/Assets/Scripts/EventManager/EventManager.cs.meta
  ARSIS-Unity/Assets/Scripts/EventManager/EventTypes.meta
  ARSIS-Unity/Assets/Scripts/EventManager/EventTypes/BaseArsisEvent.cs
  ARSIS-Unity/Assets/Scripts/EventManager/EventTypes/BaseArsisEvent.cs.meta
  ARSIS-Unity/Assets/Scripts/EventManager/EventTypes/Telemetry.cs
  ARSIS-Unity/Assets/Scripts/EventManager/EventTypes/Telemetry.cs.meta
  ARSIS-Unity/Assets/Scripts/EventManager/WebSocketClient.cs
  ARSIS-Unity/Assets/Scripts/EventManager/WebSocketClient.cs.meta
  ARSIS-Unity/Assets/XR/UserSimulationSettings/SimulationEnvironmentAssetsManager.asset
  ARSIS-Unity/Packages/packages-lock.json
Labels: HMD, mcp
