Repository BSU-SUITS-Team/ARSIS, pull requests merged in 2024-05, with the labels that each got.

#257 Spectrometry HMD
  ARSIS-Telemetry-GroundControl/groundcontrol-api/app/tss.py
  ARSIS-Unity/Assets/Resources/prefabs/Spectrometry.prefab
  ARSIS-Unity/Assets/Resources/prefabs/Spectrometry.prefab.meta
  ARSIS-Unity/Assets/Samples.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/SampleScene.unity
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/SampleScene.unity.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/TSScConnection.cs
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/TSScConnection.cs.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/TSScUI.cs
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/TSScUI.cs.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/COMM.json
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/COMM.json.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/DCU.json
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/DCU.json.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/IMU.json
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/IMU.json.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/ROVER.json
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/ROVER.json.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/SPEC.json
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/SPEC.json.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/TELEMETRY.json
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/TELEMETRY.json.meta
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/UIA.json
  ARSIS-Unity/Assets/Samples/SUITS TSSc/1.0.0/SampleTSSScene/sample_json_values/UIA.json.meta
  ARSIS-Unity/Assets/Scenes/SampleScene.unity
  ARSIS-Unity/Assets/Scripts/Components/Elements/SpecWindow.cs
  ARSIS-Unity/Assets/Scripts/Components/Elements/SpecWindow.cs.meta
  ARSIS-Unity/Assets/Scripts/Components/SettingsWindow.cs
  ARSIS-Unity/Assets/Scripts/EventManager/EventDatastore.cs
  ARSIS-Unity/Assets/Scripts/EventManager/EventTypes/BaseArsisEvent.cs
  ARSIS-Unity/Assets/Scripts/EventManager/EventTypes/Spectrometry.cs
  ARSIS-Unity/Assets/Scripts/EventManager/EventTypes/Spectrometry.cs.meta
Labels: HMD

#258 Summary Timeline
  ARSIS-Unity/Assets/Resources/prefabs/HandMenu.prefab
  ARSIS-Unity/Assets/Resources/prefabs/Notifications.prefab
  ARSIS-Unity/Assets/Resources/prefabs/ProceduresWindow.prefab
  ARSIS-Unity/Assets/Resources/prefabs/SummaryTimeline.prefab
  ARSIS-Unity/Assets/Scripts/Components/Elements/Notifications.cs
  ARSIS-Unity/Assets/Scripts/Components/Elements/Procedures.cs
  ARSIS-Unity/Assets/Scripts/Components/Elements/SummaryTimeline.cs
  ARSIS-Unity/Assets/Scripts/EventManager/EventTypes/EVA.cs
Labels: HMD

#266 Creates Procedures Modifies Spectrometry Data Display
  ARSIS-Telemetry-GroundControl/groundcontrol-api/app/routers/procedures/cable_repair.yml
  ARSIS-Telemetry-GroundControl/groundcontrol-api/app/routers/procedures/geo_sample.yml
  ARSIS-Telemetry-GroundControl/groundcontrol-api/app/routers/procedures/inspect_comm.yml
  ARSIS-Telemetry-GroundControl/groundcontrol-api/app/routers/procedures/sample_proc.yml
  ARSIS-Unity/Assets/Plugins/allGaugePackage.unitypackage.meta
  ARSIS-Unity/Assets/Resources/prefabs/ProceduresWindow.prefab
  ARSIS-Unity/Assets/Resources/prefabs/Spectrometry.prefab
  ARSIS-Unity/Assets/Scripts/Components/Elements/SpecWindow.cs
Labels: HMD, LMCC, mcp

#254 Lmcc video feed
  ARSIS-Telemetry-GroundControl/LMCC/src/routes/hololenstest/+page.svelte
  ARSIS-Telemetry-GroundControl/LMCC/src/routes/map/Panview.svelte
Labels: enhancement
